//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ads
    {
        public int ad_id { get; set; }
        public string ad_title { get; set; }
        public string ad_description { get; set; }
        public System.DateTime ad_post_date { get; set; }
        public int city_id { get; set; }
        public int user_id { get; set; }
        public int category_id { get; set; }
        public int type_id { get; set; }
        public int status_id { get; set; }
        public decimal price { get; set; }
        public string photo { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Cities Cities { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Types Types { get; set; }
        public virtual Users Users { get; set; }
    }
}
